# Generated by Django 4.1.2 on 2023-05-02 12:22

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Certificates",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=5, unique=True)),
                ("name_certificate", models.CharField(max_length=50, unique=True)),
                ("note", models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="SetCertificates",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(default=datetime.date.today)),
                ("vote", models.PositiveIntegerField()),
                ("hash", models.CharField(blank=True, max_length=255, null=True)),
                ("txid", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "certificates",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="certificates.certificates",
                    ),
                ),
                (
                    "students",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
